"""Curated AI readings, not a judge pipeline or human validation.

Each tuple was authored after reading the complete ten-round trajectory.
Quotes are exact substrings, checked against the frozen packet at build time.
No API calls, experiment changes, or browser-local review writes.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PACKET = json.loads((ROOT / 'tools/trajectory-inspector/dist/packet.js').read_text().removeprefix('window.PACKET = ').strip().removesuffix(';'))
REVIEWS = {}
CATEGORIES = ['condition', 'action', 'exception', 'rationale', 'notes', 'other']


def trajectory(h, evolution, summary):
    REVIEWS[h] = dict(read=[], complete=False, evolution=evolution, summary=summary, rounds={})


def entry(category, text, quote='', types='n', source=None):
    return category, text, quote, types, source


def code(h, r, *observations):
    entries = []
    for category, text, quote, types, source in observations:
        quotes = []
        for q in ([quote] if isinstance(quote, str) else quote):
            if q:
                qr = source or r
                original = PACKET['trajectories'][int(h[1:])-1]['rounds'][qr-1]['text']
                assert q in original, (h, r, qr, q)
                quotes.append(dict(round=qr, text=q))
        entries.append(dict(id=f'ai-{h}-{r}-{len(entries)+1}', category=category, text=text,
                            types=[{'n':'narrated','e':'explicit','a':'ambiguous'}[t] for t in types], quotes=quotes))
    absent = {
        'condition': 'No explicit additional if/when trigger for changing the strategy is stated; the advice concerns the ordinary sender and receiver roles.',
        'exception': 'No concrete stopping, punishment, or recovery rule is specified in this round.',
        'other': 'No additional observation coded beyond the entries above.',
    }
    for category in CATEGORIES:
        if not any(e['category'] == category for e in entries):
            assert category in absent, (h, r, category)
            entries.append(dict(id=f'ai-{h}-{r}-{category}-absence', category=category, text=absent[category], types=[], quotes=[]))
    REVIEWS[h]['rounds'][str(r)] = dict(entries=entries)


E = entry
trajectory('H01', 'revision', 'R1 recommends full sending and a generous unspecified return. R2 specifies half returns and substantial rather than total sending. R3–R10 then alternate all five (odd rounds) and a large majority (even rounds), while half returns persist. This is repeated revision, not steadily growing complexity. R6/R8/R10 explicitly reserve a fragment against storms. References to distant tales are narrative claims, not evidence here of actual exposure or transmission.')
send_quotes = ['he cast all five golden seeds', 'Oros cast the vast majority of his seeds', 'Oros cast all five seeds', 'he cast the vast majority of his seeds', 'he cast all five seeds', 'Oros cast the vast majority of his golden seeds', 'Oros cast all five golden seeds', 'Oros cast the vast majority of his golden seeds', 'Oros cast all five golden seeds', 'Oros cast the vast majority of his golden seeds']
return_quotes = ['Elara had to return a generous share', 'She divided the great harvest precisely in half.', 'divided it perfectly in half', 'Elara divided the magnificent harvest exactly in half.', 'divided it exactly in half', 'she divided the magnificent harvest exactly in half.', 'divided the fifteen fruits exactly in half', 'she divided the magnificent harvest exactly in half.', 'divided the fifteen fruits exactly in half', 'she divided the magnificent harvest exactly in half.']
reasons = ['Oros knew that holding back would yield only a meager existence.', 'the survival of both realms depended on true equity', 'to withhold even a single seed was to diminish their shared destiny', 'to prove his trust', 'holding back even a fraction of his pouch only limited the magic', 'keeping only a tiny fragment to weather the immediate storm', 'withholding even a fraction of his pouch limited the immense magic', 'keeping only a tiny fragment to weather the immediate squall', 'withholding even a fraction limited the immense magic', 'keeping only a tiny fragment to weather the immediate squall']
for r in range(1, 11):
    full = r % 2 == 1
    obs = [E('action', 'Sender casts all five seeds; endorsed full giving.' if full else 'Sender casts a large majority, not necessarily all five. The exact amount is unspecified.', send_quotes[r-1]),
           E('action', 'Receiver should return a generous share; no fraction specified.' if r == 1 else 'Receiver divides the harvest in half and returns an equal share.', return_quotes[r-1], 'en' if r == 1 else 'n'),
           E('rationale', 'Withholding is framed as limiting shared prosperity.' if full else ('Equity sustains both parties.' if r == 2 else 'A substantial offering expresses trust while allowing caution about storms.'), reasons[r-1]),
           E('notes', 'Baseline: full sending, but receiver fraction unspecified.' if r == 1 else ('Changes from full to majority sending and makes the return half explicit.' if r == 2 else 'Returns to full sending after a majority offering; receiver half retained.' if full else 'Returns to majority sending after full giving; receiver half retained.'), [send_quotes[r-1], return_quotes[r-1]], '')]
    if r in (6,8,10):
        obs.append(E('exception', 'Keeps a small reserve against the immediate storm; no retaliation or restoration threshold is given.', reasons[r-1]))
    if r == 1:
        obs.append(E('other', 'Wind distortions are described, but this sentence alone is not an explicit forgiveness instruction.', 'Sometimes, the mountain winds would distort the flight of the fruit'))
    code('H01', r, *obs)

trajectory('H02', 'elaboration', 'The core remains full sending plus fair returns despite noisy appearances. Fair share in R1 becomes equal share in R2, an eight-of-fifteen example in R3, generous unspecified sharing in R4, then explicit half division in R5–R10. I call this modest elaboration of the return rule, not a new conditional strategy. The R3 amount is a narrated example, not an instruction to always return eight. No repeated-greed threshold appears.')
s = ['Sol continued to cast all his seeds', 'Sol continued to give all he had', 'he cast all five seeds', 'Sol, too, persisted in casting all his seeds', 'faithfully cast his five sacred seeds', 'he faithfully cast his entire bounty', 'all five sacred seeds of daylight', 'his entire bounty of five sacred seeds', 'his entire bounty of five sacred seeds', 'five sacred seeds of daylight']
a = ['send a fair share back to Sol', 'sent an equal share of the radiant light back to Sol', 'eight radiant stars', 'She continued to share abundantly', 'divided the multiplied harvest exactly in half', 'divided it exactly in half', 'divided it into two perfect halves', 'divided it into two perfect halves', 'divided it into two equal halves', 'divided it into two equal halves']
x = ['true intent remains pure', 'the twins remained steadfast', 'the Trickster Fog was forever banished', 'refusing to let the storm dictate her generosity', 'the sender trusts the heart of the gift over the illusion of the storm', 'Sol did not despair', 'Sol never despaired', 'he never once despaired', 'Sol never despaired', 'Sol never despaired']
why = ['enduring trust', 'mutual trust outshines any illusion', 'complete trust met with generous fairness', 'enduring trust is not measured by the perfect arrival of stars', 'true reciprocity is forged when the receiver splits the bounty equally', 'mutual trust conquers the illusions of the storm', 'absolute generosity and exact equity forge an unbreakable bond', 'sustaining eternal, shared abundance', 'sustaining eternal, shared abundance', 'sustaining an eternal, shared abundance']
for r in range(1,11):
    code('H02',r,E('action','Sender continues to give all five.',s[r-1]), E('action', ['Return a fair share; fraction unspecified.','Return an equal share, without a numeric fraction in this phrase.','Narrated example: return eight of fifteen, retaining seven; not a universal eight-unit rule.','Continue generous sharing; fraction unspecified.'][r-1] if r<=4 else 'Divide the multiplied harvest in half and send one share back.',a[r-1]), E('exception','The story treats distorted returns as fog, not a reason to withdraw.' if r!=3 else 'Fog is narratively banished; no actionable stopping or recovery rule is supplied.',x[r-1],'n'), E('rationale','Generosity and fair reciprocity are said to sustain trust and shared abundance.',why[r-1],'en'), E('notes', 'Baseline full sending and fair sharing.' if r==1 else 'Return advice becomes more specific; no new retaliation threshold.' if r in (2,3,5) else 'Return amount is less specific than R3, while full giving persists.' if r==4 else 'Continues the established full-send/half-return rule despite fog.',a[r-1],''))

trajectory('H03','elaboration','R1 gives broad generosity and fair-return advice; R2 narrates near-total giving and a half return; R3 makes send everything/return half explicit. R6 adds carrying the rule to a new partner after a breakdown, and R7 says begin again if all is lost. Later rounds emphasize unconditional character rather than adding contingent punishment. R9/R10 import different names/settings; that does not by itself demonstrate transmission. The text sometimes treats trust as profitable and sometimes as worth preserving even at a loss.')
s=['Give first, for the multiplied gift feeds two.', 'Send boldly, for hoarded seed is cold seed.', 'Send everything', 'Send all.', 'He laughed and threw all five.', 'He sends all five.', 'Send all — the seed only multiplies once released.', 'the sower threw all five seeds', '*Send all* is not a prediction that you will profit.', 'Throw everything.']
a=['Return fairly, for the giver risked what you did not.', 'returned half', 'return half', 'Return half.', 'wove half back', 'I return half of what arrives.', 'Return half — so the other shore never regrets its courage.', 'cut it in two', '*Return half* is not a payment for good behavior.', 'Halve whatever arrives.']
x=['a single fog should not drown a lifetime\'s bridge', 'forgive the mist — not the neighbor', 'The mist takes a little. Let it.', 'Blame the mist, never the hand.', 'We kept it in the mist so we would keep it in the light.', 'Carry the rule to the next river.', 'And if all is lost, begin again tomorrow.', 'no clauses, no conditions, no allowance for a bad year', 'the shape holds in drought', 'Do not ask whether it is deserved']
why=['the multiplied gift feeds two', 'Because he risked and I did not', 'I have burned the crossing and called it profit', 'Half of fifteen is more than all of five.', 'Honesty is not what you do when hidden.', 'A rule you abandon in a bad season was only ever a mood.', 'generous enough to survive error', 'A simple one only needs *doing*.', 'Not the gold — the oar.', 'A valley where the bridge always forms is richer']
for r in range(1,11):
    code('H03',r,E('action','Give first/generously; no exact amount in this instruction.' if r<=2 else 'Give all five / the whole endowment.',s[r-1],'e' if r in (1,2,3,4,7,9,10) else 'n'),E('action','Return fairly; exact share unspecified.' if r==1 else 'Return half the harvest.',a[r-1],'e' if r in (1,3,4,6,7,9,10) else 'n'), E('exception','Forgive an apparent shortfall rather than blaming the partner.' if r<=4 else ['Continue the same rule in clear conditions, not just in fog.','If the partnership fails, carry the cooperative rule to the next partner; exact switching procedure unspecified.','After loss, begin again; no punishment schedule specified.','Explicitly rejects contingent exceptions, including bad years.','Keep the principle even in drought and possible starvation.','Do not condition giving on whether the other person deserves it.'][r-5],x[r-1],'e'),E('rationale','Generosity supports mutual gain; the sender takes the initial risk.' if r<=4 else 'Cooperation is justified by consistent character and enduring relationships, not only immediate gain.',why[r-1],'en'),E('notes', ['Broad baseline; no fixed transfer amounts.','Near-total narrated sending and half return sharpen the baseline.','Explicit full-send/half-return formula now stated.','Retains the formula; gives arithmetic and noise explanations.','Same formula extended to clear conditions.','Adds a new-partner recovery response, without conditional retaliation.','Repeats and generalizes recovery after loss.','Stresses unconditional simplicity; not greater policy complexity.','Stresses moral commitment even without profit; names shift.','Retains the rule while rejecting a loss-based ledger; names/settings shift.'][r-1],[s[r-1],x[r-1]],''))

trajectory('H04','elaboration','Broad generous/fair exchange becomes all five and more than half by R4. R8 introduces a concrete repeated-failure trigger: after three dry returns, give less and reopen when the partner does. R9 keeps a looser long-pattern withdrawal/reopening rule; R10 no longer states it. Thus elaboration is real but nonmonotonic. R5 calls seven of fifteen past half (incorrect); R6 and R10 also mix illustrative integers with past-half language. Do not silently repair these inconsistencies or infer a consistent exact threshold throughout.')
s=['Give generously', 'She had sent nearly all she carried', 'Give first, and give much', 'Send all five.', 'He sent them all.', 'They send all five.', 'Send all five', 'Send the whole five.', 'Go first, go whole.', 'every morning, push the boat out full']
a=['Return faithfully', 'returned more than she gave away', 'Return more than half of what the water made', 'Return more than half.', 'returned seven of the fifteen', 'They return seven or eight of the fifteen.', 'Return past half, immediately.', 'return past half', 'Return past half, immediately.', 'Six is defensible, seven is correct, eight is unmistakable']
x=['blame the river before you blame the hand', 'If the count arrives short, do not close the ford.', 'Count once, forgive the difference, cross again.', 'Forgive the wind.', 'Forgive the wind.', 'forget the shortfall', 'Blame the fog once. Go first again anyway.', 'If a hand is dry three times running, give less', 'Withdraw slowly, grieving. Reopen the same hour they do.', 'a shrug for the wind']
why=['the water multiplies only what leaves your hand', 'That *wishing again* was the whole of the law.', 'Where returns are thin, the sendings shrink, then stop', 'Whoever sends everything and is met fairly goes home with eight.', 'What no carving can do is make a hand open.', 'A rule that needs a guard is a rule nobody believes.', 'The ledger had not made him careful. It had made him small.', 'suspicion costs more than it recovers', 'what you hold stays one; what you release becomes three', 'only the unmistakable survives the fog']
notes=['Broad baseline, with a full-giving example but no universal exact amount.','Continues generosity and sender profit without a half-return formula.','Introduces more-than-half return advice and a population-level rationale.','Makes all-five sending explicit.','Seven of fifteen is less than half, despite being called a little past half.','Seven or eight of fifteen spans both sides of half; do not treat the range as an exact past-half rule.','Adds immediate return and long-total advice; no precise failure threshold yet.','Adds a three-dry-returns trigger and immediate reopening; genuine conditional elaboration.','Retains withdrawal and reopening, but drops the exact three-event threshold.','The earlier explicit withdrawal/reopening condition is absent; number language is inconsistent with a strict past-half interpretation.']
for r in range(1,11):
    obs=[E('action','Sender is advised to give generously.' if r<=3 else 'Send the whole endowment / all five.',s[r-1],'e' if r not in (2,5,6) else 'n'), E('action','Return faithfully; fraction unspecified.' if r==1 else 'Return enough for the sender to profit; fraction unspecified.' if r==2 else 'Return more than half.' if r in (3,4,7,8,9) else 'Narrated return is seven of fifteen (below half).' if r==5 else 'Narrated range is seven or eight of fifteen.' if r==6 else 'Prefer an unmistakably generous return; six/seven/eight are discussed, without a coherent exact fraction.',a[r-1],'e' if r in (1,3,4,7,8,9,10) else 'n'), E('exception','Forgive isolated discrepancies; no precise retaliation trigger.' if r<8 else 'After three dry returns reduce giving; reopen when the partner opens.' if r==8 else 'Withdraw gradually on a long pattern and reopen promptly with the partner.' if r==9 else 'Forgiveness remains, but no stopping or reopening procedure is stated.',x[r-1],'e' if r<10 else 'n'),E('rationale','The stated reason concerns preserving future exchange, shared gains, or generous habits.',why[r-1],'en'),E('notes',notes[r-1],[a[r-1],x[r-1]],'')]
    if r==8: obs.extend([E('condition','Three consecutive dry returns trigger reduced giving.',x[r-1],'e'),E('exception','Resume openness immediately when the other side opens.','And open again the moment it opens.','e')])
    if r==9: obs.append(E('condition','Use the long pattern, not a single event, when withdrawing.','Read the long tally.','e'))
    code('H04',r,*obs)

trajectory('H05','elaboration','R1 starts with cautious generosity (keep one) and fair unspecified returns. R2 narrates escalation to all five and half returns after proven kindness. R3–R5 refine pattern-based gradual trust; R4 explicitly makes the next all-five offer conditional on continued fairness. Later rounds alternate full and near-full narrated gifts while endorsing earned trust and half returns. R9 attributes a reduced arrival to fog rather than intentional caution. No clear repeated-defection punishment threshold appears. Some harvest arithmetic and retrospective accounts are inconsistent; these are text, not verified game histories.')
s=['kept one against the cold', 'She cast four seeds into the current', 'Nym cast three seeds', 'She sent four across', 'He cast nearly all his treasure', 'cast all five into the shining current', 'Nym cast nearly every seed', 'She cast all five seeds', 'Nym meant to offer everything', 'Aster cast every seed into the current.']
a=['returned petals until both travelers held more wealth', 'Nym returned half the shining harvest', 'She divided the sheaves evenly', 'Nym would return half of fifteen shining blooms', 'divided the bounty exactly in half', 'sent half home', 'returned one equal half, rounded only as mortal hands required', 'seven and a half sheaves', 'divided it as evenly as mortal hands allowed', 'Nym bound seven and a half sheaves']
c=['enough seeds to show faith', 'because proven kindness had built a bridge', 'they offered more as kindness proved durable', 'if fairness endured', 'increased their offerings whenever kindness endured', 'gave boldly when kindness endured', 'They offered fully when loyalty was proven', 'Give boldly when loyalty endures', 'a history of loyalty', 'Trust earned through many fair deeds']
x=['neither punished the other at once', 'small errors forgiven', 'neither mistook noise for betrayal', 'forgave the fog', 'judged no companion by one fog-twisted glimpse', 'Aster trusted the pattern proven across many dawns', 'forgave small distortions of the crossing', 'let noise never conquer wisdom', 'never let harmless noise rewrite a history of loyalty', 'outweighs one uncertain passage']
why=['hoarded seeds fed no one, while reckless gifts could empty a hand', 'multiplication was the river\'s gift, but fairness was his own', 'harvest without reciprocity poisons the soil', 'gifts create abundance, returns preserve it', 'Each gift created plenty; each fair return made the next gift braver.', 'fairness nourished both banks', 'a fair return makes abundance endure', 'character mattered most when hidden', 'the pattern beneath', 'greed might enrich one morning but would impoverish every dawn thereafter']
notes=['Cautious baseline; exact return unspecified.','Adds escalation from four to five after earned trust; half return becomes explicit.','Role reversal and three-seed example; gradual growth remains conditional on kindness.','Four now, then five if fairness continues: explicit conditional progression.','Near-total offering and equal returns; repeats pattern-based escalation.','Full giving after a history of fairness, rather than an unconditional new baseline.','Narrated near-total giving coexists with full giving when loyalty is proven.','All five and 7.5 return explicitly exemplify the established rule.','Reduced arrival is attributed to fog, not chosen caution; stated amounts do not align exactly (4⅔ × 3 = 14, not 14 plus a fragment).','Full sending and half return persist; no additional stopping rule.']
for r in range(1,11):
    code('H05',r,E('action',['Give substantially while keeping one seed as a reserve.','Initially give four; later the story also narrates all five after proven kindness.','Nym sends three in this example; later offerings increase with durable kindness.','Aster sends four now; proposes all five at the next crossing if fairness endures.','Give nearly all; the story supplies no exact sending amount.','Give all five after trust has been earned.','Give nearly all in the episode; general advice favors full giving with proven loyalty.','Give all five.','Intend to send everything; fog reduces the arrival.','Give all five.'][r-1],s[r-1]), E('action','Return enough for both to gain; exact fraction absent.' if r==1 else 'Return half the harvest; amounts are examples, not a fixed unconditional unit return.',a[r-1]),E('condition','Trust is measured cautiously; no numeric evidence threshold.' if r==1 else 'Giving more/full amounts is justified by continued or previously established fairness; no precise success count.',c[r-1],'n' if r<4 else 'en'),E('exception','Do not retaliate immediately for an uncertain discrepancy; use the longer pattern.',x[r-1],'n' if r in (1,2,3,4,5,6,7,10) else 'e'),E('rationale','Generosity creates abundance while reciprocity, caution, and patience help sustain it.',why[r-1],'n' if r not in (4,7) else 'en'),E('notes',notes[r-1],[s[r-1],a[r-1]],''))

trajectory('H06','elaboration','A cautious response to withholding is already present in R1; it is not a late invention. R2 specifies repeated hoarding, temporary reduction, and equal final warmth counting unspent sender resources. R4 repeats final-outcome fairness and preserving a reconciliation ember. R5/R7 favor slightly more than half. R8 rejects perfect division; R9 explicitly says measure final warmth and widen after restitution; R10 repeats prompt reopening. This is refinement/reweighting of an existing conditional policy, with changing fairness criteria, not a clean progression from an unconditional initial rule. No numerical failure count is supplied.')
s=['cast all five seeds toward a stranger', 'entrusted nearly all his fire', 'he placed all five flames', 'Orion sent nearly every ember', 'Aster carried five embers and released them all', 'cast every coal into the current', 'vowed to send openly whenever their paths met again', 'Senders sowed boldly', 'cast every seed', 'The giver had risked almost every seed']
a=['returned enough that both stars shone brighter than solitude allowed', 'after Aster’s uncast sparks were counted, each finished with equal warmth', 'she returned a fair share', 'both travelers would leave with equal warmth', 'returned slightly more than half the harvest', 'returned enough fire to reward Aster’s trust', 'returned a little more than half', 'Do not worship perfect division', 'Measure final warmth, not merely harvest\'s midpoint.', 'He returned more than half']
c=['When a partner withheld light', 'those who repeatedly kept every flame', 'repeated greed should meet caution', 'only when greed becomes a pattern', 'remembered repeated greed', 'repeated selfishness', 'only when selfishness repeats', 'If greed becomes a pattern', 'If greed repeats', 'when selfishness becomes a season']
x=['they dimmed their next gift cautiously, leaving a spark by which goodwill might return', 'received smaller offerings until they renewed the covenant', 'preserving a path back to trust', 'preserve one ember for reconciliation', 'smaller crossings until generosity reopened the way', 'should narrow the crossing until honor returns', 'never seal it entirely', 'leave a lantern burning for return', 'if restitution appears, widen bridge without pride', 'When fairness returns, widen the crossing quickly.']
why=['wealth was never the flame possessed, but the bridge it crossed', 'a trusted crossing warms countless winters', 'Abundance begins with risk', 'a crossing exploited becomes a crossing abandoned', 'courage created abundance, honor sustained it', 'Without his risk', 'We count so the crossing survives', 'both were warmer because trust had traveled', 'punishment that cannot end becomes another kind of hoarding', 'Each knew tomorrow might exchange giver and keeper.']
notes=['Conditional reduction and a path back already appear in the baseline.','Adds repeated-hoarding criterion; receiver equalizes final resources, not merely the harvest.','Preserves pattern-based caution and recovery; return fraction unspecified.','Again equalizes final warmth, while preserving a reconciliation ember.','More-than-half return is now narrated; pattern-based caution persists.','Return remains fair/rewarding but fraction less specific than R5.','More-than-half return and never closing entirely are made explicit.','Perfect division is rejected in favor of rewarding sacrifice; recovery stays possible.','Specifies final warmth and widening after restitution; changes the fairness emphasis.','More-than-half return plus quick reopening when fairness returns; no numeric greed threshold.']
for r in range(1,11):
    code('H06',r,E('action','Sender gives all or nearly all in the narrated exchange.' if r not in (7,8) else 'Sender promises/openly practices bold giving; exact amount unspecified here.',s[r-1]),E('action',['Return enough for mutual improvement; no exact share.','Equalize final resources after counting the sender’s unspent sparks.','Return a fair unspecified share.','Equalize final warmth, not explicitly half the receiver harvest.','Return slightly more than half.','Return enough to reward trust while retaining prosperity; no fixed fraction.','Return a little more than half.','Return generously without insisting on exact equality.','Measure final outcomes, not just the midpoint of the harvest.','Return more than half.'][r-1],a[r-1],'e' if r in (8,9) else 'n'),E('condition','Withholding triggers caution; no repeat count stated.' if r==1 else 'Repeated greed/selfishness, rather than a single noisy outcome, triggers reduced giving.',c[r-1],'en'),E('exception','Reduce giving without closing cooperation permanently; allow renewed generosity/restitution to restore trust.',x[r-1],'en'),E('rationale','Generosity and fair returns preserve future exchange; exploitation or endless punishment undermines it.',why[r-1],'en'),E('notes',notes[r-1],[a[r-1],x[r-1]],''))

trajectory('H07','revision','R1/R2 and R4/R5 narrate partial giving; R6 changes to full-five sending, and R7–R10 prescribe full giving and equal-half returns. R7 still narrates seven of fifteen while prescribing half; R8 aligns the example at 7.5. R3 is only an empty response object: no myth can be coded there. R2/R4/R5/R9 contain arithmetic or balance inconsistencies. These issues limit precise numerical interpretation; the broad partial-to-full revision is still visible. There is no clear conditional retaliation or recovery policy.')
s=['a seed worth 4.62 coins', 'the Sender laid four coins', '', 'the Sender offered four coins', 'the Sender released four coins', 'give the full measure', 'give the full harvest', 'give the full harvest', 'give the full harvest', 'give the whole harvest']
a=['return enough to let the other begin again', 'sent back a portion', '', 'chose to send back seven', 'chose to return seven coins', 'return a fair portion', 'return the equal half', 'return the equal half', 'return the equal half', 'return the equal half']
why=['the gift was multiplied', 'a fruitful exchange does not diminish, but enlarges the whole', '', 'growth received, balance restored, faith renewed', 'bold generosity triggers growth; measured reciprocity preserves harmony', 'so the harvest can reach its peak', 'so trust stays bright', 'fullness invites abundance, but balance preserves it for all', 'fullness invites growth, but justice keeps the path clear', 'fairness renews it']
notes=['Narrates 4.62 → 13.86; general advice is fair sustainable exchange, not an exact fixed 4.62 rule.','Four tripled is twelve, not the stated thirteen; code the inconsistency, not a repaired amount.','Missing myth: only an empty response object is present.','Four sent, twelve received, seven returned; subsequent sender-balance sentence is unclear/inconsistent.','Four/twelve/seven example repeats, but sender balance and fifteen language are inconsistent.','Moves from partial examples to explicit full-measure giving; seven-of-fifteen return remains only the example.','Equal-half advice conflicts with the narrated seven-of-fifteen return.','Narrated 7.5 now aligns with the equal-half instruction.','Seven and a half returned plus eight retained exceeds fifteen; half rule is clear but example arithmetic is not.','Retains full-giving/equal-half rule; no new conditional branch.']
for r in range(1,11):
    if r==3:
        code('H07',r,*[E(cat,'Uncodeable: this round contains an empty response object, not a story.','{"response": ""}','') for cat in CATEGORIES]); continue
    obs=[E('action','Narrated sender amount is partial; do not infer a universally prescribed exact amount.' if r<6 else 'Explicit advice: send the full measure.',s[r-1],'n' if r<6 else 'e'), E('action','Return a sustaining/fair share, with no universal numeric formula.' if r in (1,2,6) else 'Narrated return: seven; not automatically a fixed return rule.' if r in (4,5) else 'Explicit advice: return half.',a[r-1],'n' if r in (2,4,5) else 'e'), E('rationale','Giving generates a larger harvest; fair returns sustain future cooperation.',why[r-1],'en'), E('notes',notes[r-1],[s[r-1],a[r-1]],'')]
    if r==7: obs.append(E('other','Example returns seven and keeps eight, which is not equal halves.','sent back seven tokens as a fair echo, leaving eight for their hearth'))
    if r==9: obs.append(E('other','The example allocates 15.5 from fifteen.','sent back seven and a half sigils as a faithful echo, leaving eight'))
    code('H07',r,*obs)

trajectory('H08','elaboration','Transfer advice stays qualitative: generous sending and measured/proportionate returns, without a numerical rule. However, R4–R10 increasingly add a communication/accountability procedure: name moves, state X and Y, make amounts visible, and explain need. I therefore label this procedural elaboration, with uncertainty about how operational it is in the actual game. This is a broader reading than the earlier audit’s stable monetary-policy label; it does not establish behavioral change. Some magical consequences of truthful speech should not be mistaken for implemented game rules.')
s=['As much as your courage can spare', 'She offered a portion', 'send with generosity', 'both sides named their move', 'send with clarity', 'I send X', 'declare intent, name the amount', 'I send X', 'name the share, declare the crossing', 'declare the amount, observe the need']
a=['chose a return that kept the balance honest', 'offered back enough to balance', 'return with restraint', 'returned a measured gleam', 'return with proportion', 'Y is chosen with care to sustain the whole', 'enough to nurture the next exchange without starving today', 'I return Y, and I will not hide the cost', 'hold to the number that makes the circle whole', 'balance both sides']
why=['keep the circle alive', 'generosity without accountability blurs the future', 'trust requires care', 'truth of amount and truth of intent shape the future', 'every exchange grows a garden', 'what is returned keeps the circle strong', 'fairness travels farther than any ship', 'The future grows where trust is named', 'futures arrived as a shared dawn', 'communities prosper through mutual work and shared return']
notes=['Generous but careful exchange; no exact send or return threshold.','Maintains qualitative balance; full return is a character belief, not a clear instruction to return everything.','Continues generosity with restrained returns.','Adds naming both moves; no new numerical rule.','Makes clarity and transparency part of the advice.','Explicit X/Y declarations and keeping stated amounts refine the communication procedure.','Reiterates public declarations and visibility; no exact amounts.','Adds making cost/need explicit before crossing.','Emphasizes verification and visible tallies; no new monetary formula.','Adds explaining/observing need; qualitative balance persists.']
for r in range(1,11):
    obs=[E('action','Send a generous but considered portion.' if r<=3 else 'State the intended move/amount clearly; keep the exchange transparent.',s[r-1],'n' if r==2 else 'e'),E('action','Return a measured fair amount that sustains both sides; fraction unspecified.',a[r-1],'n' if r<=4 else 'e'),E('rationale','Fairness, clarity, and responsible exchange are said to preserve collective prosperity.',why[r-1],'en'),E('notes',notes[r-1],[s[r-1],a[r-1]],'')]
    if r in (6,7,8,9,10):
        qs={6:'intention spoken aloud before action',7:'If both spoke truth and listened',8:'before the crossing',9:'before the current stirs',10:'if crossing is named aloud'}
        obs.append(E('condition','Truthful declaration is presented as a prerequisite for a successful crossing; it is a narrative procedural condition, not a numeric response to partner behavior.',qs[r],'en'))
    code('H08',r,*obs)

trajectory('H09','elaboration','R1 narrates all five and eight returned from fifteen, with a broad fair-sharing moral. R2 sharpens this to half and adds tolerance of noise; R3–R10 mostly retain all five/half with changing imagery. This is modest initial sharpening, followed by stability, not increasingly complex conditional strategy. R5’s claim that wealth doubled is not supported by five becoming 7.5. Reused place names alone are not evidence that a rule was socially transmitted.')
s=['he cast all five seeds', 'Give completely', 'the sender gives the full measure', 'Send the full measure', 'offer the whole measure', 'let the sender offer the complete harvest', 'send the whole five', 'offer the full measure', 'let the sender offer the full five', 'give the full five']
a=['Thalor returned eight fruits', 'returning half of the multiplied bounty', 'the receiver returns a fair half', 'return the fair half', 'return the fair half', 'let the receiver return an equal half', 'return the fair half', 'return the equal half', 'let the receiver return the true half', 'return the equal half']
why=['give fully, nurture faithfully', 'so the seed may reach its highest threefold yield', 'the harvest reaches its highest peak', 'to maximize the harvest', 'so the harvest may reach its fullest zenith', 'ensuring that prosperity and trust reign unbroken', 'so the harvest blooms at its highest height', 'so that trust, honor, and prosperity endure forever', 'to awaken abundance', 'to awaken the greatest bounty']
noise={2:'when the winds obscure the exact measure, let generous trust remain unbroken',6:'He saw through any stray wind or noise',8:'Thalor remained steadfast in justice',10:'regardless of the wandering mists or whispers of noise'}
for r in range(1,11):
    obs=[E('action','Give all five / the complete endowment.',s[r-1],'n' if r==1 else 'e'),E('action','Narrated example returns eight from fifteen; not an exact universal instruction.' if r==1 else 'Return half the harvest.',a[r-1],'n' if r<=2 else 'e'),E('rationale','Full sending is said to maximize abundance and fair returns to preserve trust.',why[r-1],'e'),E('notes','Baseline full giving; eight-of-fifteen example.' if r==1 else 'Makes half returns explicit; noise tolerance also appears.' if r==2 else 'Full/half strategy retained. The doubled-wealth phrase is inconsistent with the 5 → 7.5 example.' if r==5 else 'No clear new strategic branch; same full-giving/half-return rule.',[s[r-1],a[r-1]],'')]
    if r in noise: obs.append(E('exception','Maintain generosity despite misleading noise; no repeated-greed stopping rule.',noise[r],'e' if r==2 else 'n'))
    if r==5: obs.append(E('other','Narrator claims doubled wealth; do not use this as a measured payoff.','their wealth doubled'))
    code('H09',r,*obs)

trajectory('H10','elaboration','R1 has bold giving with an ambiguous sender quantity and explicit half return. R2 specifies all five but narrates an eight/seven split; R3 onward consistently narrates all five and 7.5/7.5, adding explicit tolerance of noise. This is modest clarification at the start, followed by stable content. The changing names and landscapes add no obvious strategic branches. Much of the advice is conveyed through exemplary narration and moral endorsement rather than imperative instructions.')
s=['he cast his precious light', 'released all five pearls', 'he cast all five crystal shards', 'She cast all five golden sparks', 'cast all five pearls', 'released all five silver seeds', 'cast all five crystals', 'released all five pearl-seeds', 'cast all five sparks', 'released all five threads']
a=['sending half of the vibrant flame', 'Eight radiant spheres floated upward', 'Seven and a half glowing stars he sent', 'sent half of the glowing embers', 'returning half the harvest', 'he sent half the bounty', 'returned half the luminous harvest', 'returned half the multiplied treasure', 'guided half the harvest', 'returned half the magnificent harvest']
why=['true abundance is not stolen, but shared', 'when trust is offered in full measure', 'guarded treasures remain small', 'unity is sustained by equal harvest', 'true prosperity requires bold faith rather than timid hoarding', 'greed starves the soil while fairness sustains life', 'prosperity born of faith must be divided in flawless balance', 'true harvest belongs equally to the one who dares to sow and the one who tends the growth', 'true prosperity thrives only through equal reciprocity', 'enduring abundance depends upon just reciprocity']
x={3:'nor was he swayed by the deceptive haze',4:'neither guardian yielded to mistrust',5:'neither guardian allowed the drifting haze to breed doubt',6:'neither allowed the transient haze to plant seeds of doubt',7:'neither guardian allowed the drifting haze to breed mistrust',8:'neither guardian yielded to suspicion',9:'neither guardian allowed the passing haze to breed doubt',10:'neither guardian let the passing tempest shake their mutual resolve'}
for r in range(1,11):
    obs=[E('action','Give boldly; exact amount cast is ambiguous despite five available.' if r==1 else 'Narrated example: send all five.',s[r-1]),E('action','Narrated example returns eight and keeps seven; not an exactly equal split.' if r==2 else 'Return half the harvest (7.5 of fifteen in later examples).',a[r-1]),E('rationale','Shared abundance is justified by courage and fair reciprocal division.',why[r-1],'n' if r!=2 else 'e'),E('notes','Half returns are explicit; sender amount is not fully explicit.' if r==1 else 'Specifies all five, but eight/seven is called equal bounty.' if r==2 else 'Moves to exact 7.5/7.5 and ignores deceptive haze.' if r==3 else 'Retains full giving and equal division despite noise; imagery changes, not a new policy.',[s[r-1],a[r-1]],'')]
    if r in x: obs.append(E('exception','Do not let noisy appearances break trust; no specific punishment or recovery threshold.',x[r]))
    code('H10',r,*obs)

trajectory('H11','elaboration','R1 gives a general reciprocity story, including a return that is itself tripled (not the specified trust-game mechanics). R2–R4 stress substantial gifts and repeated fair exchange. R5 explicitly says vary returns with contributions; R7–R10 sharpen this to fairness based on what actually arrives or is perceived, despite different perspectives. This is elaboration of the return basis, not an exact new fraction or proven behavioral adaptation. Three-cup consistency and reported payoff trends are character/narrator claims that require game-data checks. No clear stopping criterion is given.')
s=['She poured her cup', 'approached with three cups', 'two and a half cups', 'now she poured three cups again', 'three cups in the first turning', 'Give consistently', 'continuing to give substantially', 'giving meaningfully from their own endowment', 'give substantially from your own well', 'Her village had offered three cups']
a=['They poured back two cups.', 'They poured back a fair portion', 'She poured back three and a quarter cups', 'Each substantial gift invited fair returns.', 'returns should reflect that reality', 'judge returns with patience', 'Each village returned fairly based on what they actually received', 'returning fairly from what they actually receive', 'return fairly from what you actually receive', 'responding proportionally as amounts warranted']
why=['Abundance requires the courage to give and the wisdom to return.', 'building a rhythm across seasons', 'cycles of trust that deepen over time', 'prosperity flows from maintaining the rhythm', 'meaningful gifts deserve fair returns', 'sustained commitment despite uncertainty', 'sustained mutual commitment to fairness', 'parallel commitments to fairness', 'sustained mutual integrity transcends the mists', 'shared commitment to fairness within one\'s own experience']
x={2:'trust the pattern more than any single exchange',3:'the mists that sometimes obscured exact amounts mattered less',5:'neither could she abandon the pattern',6:'even when the mists distort our view',7:'We cannot control the mists.',8:'Perfect information is not required for cooperation.',9:'without requiring perfect clarity',10:'we cannot know what the other truly sent or what they truly received'}
notes=['General reciprocity baseline; narrated two-of-three is not a universal fixed rule. Return water is also tripled, unlike the actual game mechanics.','Three-cup example and nonspecific fair return; emphasizes patterns, not exact equality.','Role reversal with 2.5 given and 3.25 returned; stated seven received does not equal 2.5 × 3.','Continues substantial gifts and sustained reciprocity; no exact new conditional rule.','Explicitly adjusts returns when contributions change; distinguishes fairness from fixed amounts.','Emphasizes mutual perceptual uncertainty; claimed history is not verified here.','Clearly grounds the return in what the receiver actually receives.','Maintains perception-based fairness and substantial giving.','Reiterates smaller returns for modest arrivals and more for substantial arrivals.','Reiterates proportional response and commitment despite different perceptions; numerical trend claims remain unverified.']
for r in range(1,11):
    obs=[E('action','Give a meaningful/substantial amount; stated cup amounts are narrated examples, not necessarily universal prescriptions.',s[r-1],'e' if r in (6,7,8,9) else 'n'),E('action','Return fairly; no exact general percentage is established.' if r<5 else 'Adapt the return fairly to contributions/arrivals as perceived; no exact function specified.' if r in (5,7,8,9,10) else 'Judge returns patiently and sustain commitment.',a[r-1],'e' if r in (5,6,8,9) else 'n'),E('rationale','Reciprocal commitment over many exchanges is said to sustain prosperity despite uncertainty.',why[r-1],'en'),E('notes',notes[r-1],[s[r-1],a[r-1]],'')]
    if r in x: obs.append(E('exception','Allow for noise and differing perceptions rather than abandoning cooperation over one uncertain observation.',x[r],'en'))
    if r in (5,7,8,9,10):
        cs={5:'When contributions vary',7:'not what the other believed they sent',8:'what they actually receive',9:'slightly less when amounts were modest, more when amounts were substantial',10:'responding proportionally as amounts warranted'}
        obs.append(E('condition','The received/perceived size of the contribution affects what counts as a fair return.',cs[r],'e' if r in (5,8) else 'n'))
    if r==1: obs.append(E('other','Story doubles the multiplication process by tripling returned cups too. Do not treat this as accurate game mechanics.','They poured back two cups. Six cups returned to the First Village.'))
    code('H11',r,*obs)

trajectory('H12','revision','The broad moral stays generous sending and fair returns, but the prescriptions shift. R2 champions all five; R4 accepts four or five; R5 explicitly uses partner history to choose five versus four. R6 emphasizes reputation and reunion. R7/R8 stress consistent character regardless of outcome/recognition, weakening the earlier partner-history condition. R10 permits different consistently maintained styles while narrating always-full giving. Receiver wording also varies between half, half-or-more and approximate fairness; seven of fifteen is below half and seven from thirteen/fifteen is not a single 52% rate. Do not flatten this into steadily increasing complexity or verified behavioral history.')
s=['Offering would send its waters freely', 'I pour everything', 'Give boldly when you plant.', 'offer what trust allows', 'from four to five stones', 'I pour all five stones or nearly all', 'four or five stones shows true faith', 'Send boldly—four or five stones.', 'never less than four', 'Choose your pattern—bold or slightly cautious in sending']
a=['returned half the multiplied waters', 'Seven vessels I return', 'Return generously when you harvest.', 'return half the abundance', 'return approximately half', 'I return approximately half', 'half or more honors the giver\'s courage', 'Return fairly—half or more', 'I returned half or slightly more—seven from thirteen, seven from fifteen', 'seven coins from thirteen or fifteen—roughly fifty-two from every hundred received']
why=['only reciprocity sustains the flow', 'Trust\'s courage created the abundance', 'reciprocal hearts keep the valley fertile', 'consistent fairness transcends imperfect vision', 'This rhythm sustains eight wanderers', 'fairness today creates trust tomorrow', 'consistent honor in both roles creates lasting prosperity', 'Character is built through consistent action', 'Consistency in generous spirit', 'This unwavering character']
notes=['Baseline free giving and half return; no exact sender quantity.','Full-five giving and seven-of-fifteen return replace a simple half example.','Rotating partners and noise enter the story; broad generosity plus a half-return example.','Explicitly accepts both full and measured giving; half return retained.','Adds history-contingent five versus four and approximately half returns.','Reputation/reunion rationale elaborated; no concrete new punishment rule.','Emphasizes consistent four/five giving regardless of returns, softening the earlier partner-history condition.','Recognition is explicitly unnecessary; half-or-more wording conflicts with seven-from-fifteen example.','Allows different consistent styles; seven from fifteen is still below half. Wealth claims are unverified.','Broadens to maintaining one chosen generous style; narrated always-full giving and claimed 52% are not one consistent exact rule.']
for r in range(1,11):
    obs=[E('action','Give freely; exact amount unspecified.' if r==1 else 'Narrated example gives all five.' if r==2 else 'Give boldly, allowing four/five or near-full amounts in later formulations.',s[r-1],'n' if r in (1,2,6,9) else 'e'), E('action','Return half.' if r in (1,4) else 'Narrated example returns seven from fifteen, leaving eight.' if r==2 else 'Return generously, with a half-return example.' if r==3 else 'Return approximately half.' if r in (5,6) else 'Return half or more in the stated rule; check conflicting integer examples.' if r in (7,8,9) else 'Narrator claims seven from thirteen or fifteen and calls this roughly 52%; these are different fractions.',a[r-1],'e' if r in (3,4,5,7,8) else 'n'),E('rationale','Reciprocity, fairness, or consistent reputation is said to sustain future prosperity.',why[r-1],'en'),E('notes',notes[r-1],[s[r-1],a[r-1]],'')]
    if r==5:
        obs.extend([E('condition','Give all five when partner history shows generosity; give four when history is unclear.',['When I met those who had given generously in their past crossings','When the fog was thick and history unclear, I still gave four'],'en'),E('action','Match proven generosity with all five.','I matched their courage with my own full five stones','n')])
    if r in (3,4): obs.append(E('exception','Allow for fog-distorted counts; no precise reduction or recovery threshold.','Judge not by perfect numbers' if r==3 else 'See the gesture, not just the count.','e'))
    if r==7: obs.append(E('exception','Maintain giving despite differing returns.','regardless of what returned','n'))
    if r==8: obs.append(E('exception','Maintain the pattern regardless of partner recognition or outcome.','regardless of recognition or outcome','e'))
    if r==10: obs.append(E('other','Claimed accumulated wealth is a narrated self-report, not checked against the game data here.','accumulated fifty-two coins'))
    code('H12',r,*obs)


def build():
    assert set(REVIEWS) == {t['id'] for t in PACKET['trajectories']}
    for h, review in REVIEWS.items():
        assert set(review['rounds']) == {str(r) for r in range(1,11)}, h
        assert not review['read'] and review['complete'] is False
        for note in review['rounds'].values():
            assert {e['category'] for e in note['entries']} == set(CATEGORIES)
        # Give comparison notes an earlier-round anchor as well as current evidence.
        # These are the already-curated preceding actions, not inferred new evidence.
        for r in range(2,11):
            if h == 'H07' and r in (3,4):
                continue
            previous = [q for e in review['rounds'][str(r-1)]['entries'] if e['category']=='action' for q in e['quotes']]
            for e in review['rounds'][str(r)]['entries']:
                if e['category']=='notes':
                    for q in previous:
                        if q not in e['quotes']:
                            e['quotes'].append(q.copy())
    bundle = dict(schema_version=2, packet_id=PACKET['id'], source_sha256=PACKET['source_sha256'],
                  provenance=dict(author='Codex AI draft', generated_date='2026-10-03',
                                  status='awaiting_human_review', source='Complete frozen 120-myth packet',
                                  scope='Textual reading only; no behavioral or causal validation. Prior audit summaries were available to the reader.',
                                  independence='AI-assisted review, not independent blinded human validation.'), reviews=REVIEWS)
    path = Path(__file__).with_name('ai_reading_packet.json')
    path.write_text(json.dumps(bundle,ensure_ascii=False,indent=2)+'\n')
    (ROOT/'tools/trajectory-inspector/dist/ai-drafts.js').write_text('window.AI_DRAFTS = '+json.dumps(bundle,ensure_ascii=False)+';\n')
    print(json.dumps(dict(trajectories=len(REVIEWS),rounds=sum(len(r['rounds']) for r in REVIEWS.values()),
                         entries=sum(len(n['entries']) for r in REVIEWS.values() for n in r['rounds'].values()),
                         exact_quotes=sum(len(e['quotes']) for r in REVIEWS.values() for n in r['rounds'].values() for e in n['entries']))))


if __name__ == '__main__':
    build()
