#!/usr/bin/env python3
"""Robustness checks for the one positive result in myth_text_predictiveness.py.

The opening send (myth->game, round 1) is predicted by the amount a myth names
(PR #4's extracted rules) and by nothing else. Three checks:

1. Probe: can the whole-text embedding and the word counts recover the named
   amount at all? Ridge from each representation to PR #4's `send_amount`, on
   every myth that names one, 5-fold cross-validation grouped by run. A high R^2
   means the opening failure of those representations is a sample-size problem
   (213 decisions), not missing information.
2. Opening send, per author family and setting: gain in cross-validated R^2 from
   the named amount alone (plus a missing flag) and from all PR #4 fields, with a
   95% interval from resampling whole runs (1,000 draws of the out-of-fold
   predictions).
3. Clustering: how many runs the agents behind each named amount come from, and
   the round-1 send by named amount and moral label split by setting.

Outputs: docs/figures/myth_text_predictiveness_20260930/opening_checks.md
No API calls.

  python3 analyses/myth_text_opening_checks.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import RidgeCV
from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import StandardScaler

sys.path.insert(0, str(Path(__file__).resolve().parent))
from myth_text_predictiveness import DATA, KEY, LABELS, OUT, RULES, rule_features  # noqa: E402

ALPHAS = np.logspace(-2, 7, 19)


def oof(x: np.ndarray, y: np.ndarray, groups: np.ndarray) -> np.ndarray:
    pred = np.empty_like(y)
    for tr, te in GroupKFold(5).split(x, y, groups):
        sc = StandardScaler().fit(x[tr])
        pred[te] = RidgeCV(alphas=ALPHAS).fit(sc.transform(x[tr]), y[tr]).predict(sc.transform(x[te]))
    return pred


def r2(y: np.ndarray, p: np.ndarray) -> float:
    return 1 - np.sum((y - p) ** 2) / np.sum((y - y.mean()) ** 2)


def run_boot(y, p_base, p_full, groups, n=1000, seed=0) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    runs = np.unique(groups)
    idx = {g: np.flatnonzero(groups == g) for g in runs}
    gains = []
    for _ in range(n):
        s = np.concatenate([idx[g] for g in rng.choice(runs, len(runs))])
        gains.append(r2(y[s], p_full[s]) - r2(y[s], p_base[s]))
    return tuple(np.quantile(gains, [0.025, 0.975]))


def main() -> None:
    lines = ["# Opening-send robustness checks", "",
             "Generated by `analyses/myth_text_opening_checks.py`. Myth→game only.", ""]
    myths = pd.read_csv(DATA / "myths.csv")
    myths["text"] = myths.text.fillna("")
    emb = np.load(DATA / "embeddings_mpnet.npy")
    rules = pd.read_csv(RULES)
    tfidf = TfidfVectorizer(ngram_range=(1, 2), min_df=5, sublinear_tf=True).fit_transform(myths.text)

    # 1. probe
    amt = myths[KEY].merge(rules[KEY + ["send_amount"]], on=KEY, how="left").send_amount.to_numpy()
    has = ~np.isnan(amt) & (myths.n_words >= 20).to_numpy()
    y, g = amt[has], myths.run_id.to_numpy()[has]
    lines += ["## 1. Can the text representations recover the named amount?", "",
              f"Myths that name an amount: {has.sum():,}. Cross-validated R² (folds by run):", "",
              "| Representation | R² | Named amount mean (±std) |", "|---|---:|---:|"]
    svd = TruncatedSVD(100, random_state=0).fit_transform(tfidf[has])
    for name, x in [("embedding (768 dims)", emb[has]), ("word counts (100 SVD dims)", svd)]:
        lines.append(f"| {name} | {r2(y, oof(x, y, g)):.2f} | {y.mean():.2f} (±{y.std():.2f}) |")
    lines.append("")

    # 2. opening send, per family and setting
    dec = pd.read_csv(DATA / "decisions.csv")
    labels = pd.read_csv(LABELS)
    feats = rule_features(myths)
    m = myths.reset_index().rename(columns={"index": "row"})
    o = m[(m.task_order == "myth_game") & (m["round"] == 1) & (m.n_words >= 20)]
    o = o.merge(dec[dec.role == "investor"][KEY + ["sent"]], on=KEY)
    o = o.merge(labels[KEY + ["label_glm_5_2"]], on=KEY).merge(rules[KEY + ["send_amount"]], on=KEY, how="left")
    o["setting"] = o["size"].astype(str) + "-agent " + o["mixed"].map({True: "mixed", False: "homogeneous"})
    lines += ["## 2. Opening send: gain in R² over family + composition cell", "",
              "95% interval from resampling whole runs (1,000 draws).", "",
              "| Authors | Senders | Runs | Named amount alone | All PR #4 fields |", "|---|---:|---:|---|---|"]
    subsets = [("all families", o)] + [(f, d) for f, d in o.groupby("family") if d.sent.std() > 0]
    for name, d in subsets:
        yy, gg = d.sent.to_numpy(float) / 5, d.run_id.to_numpy()
        base = pd.concat([pd.get_dummies(d["size"].astype(str) + d.composition, dtype=float),
                          pd.get_dummies(d.family, dtype=float)], axis=1).to_numpy()
        pb = oof(base, yy, gg)
        cells = []
        for x in [feats[d.row.to_numpy(), :2], feats[d.row.to_numpy()]]:
            pf = oof(np.hstack([base, x]), yy, gg)
            lo, hi = run_boot(yy, pb, pf, gg)
            cells.append(f"{r2(yy, pf) - r2(yy, pb):+.2f} [{lo:+.2f}, {hi:+.2f}]")
        lines.append(f"| {name} | {len(d)} | {d.run_id.nunique()} | {cells[0]} | {cells[1]} |")
    lines.append("")

    # 3. clustering and per-setting descriptives
    o["named"] = o.send_amount.map(lambda v: "none" if np.isnan(v) else f"{v:g}")
    lines += ["## 3. Round-1 send by named amount and by moral label, per setting", "",
              "Mean send (±std), senders, runs.", ""]
    for col, title in [("named", "Named amount"), ("label_glm_5_2", "GLM-5.2 moral label")]:
        t = (o.groupby(["family", "setting", col])
             .agg(mean=("sent", "mean"), sd=("sent", "std"), n=("sent", "size"), runs=("run_id", "nunique"))
             .reset_index())
        t["cell"] = t.apply(lambda r: f"{r['mean']:.2f} (±{0 if np.isnan(r.sd) else r.sd:.2f}), n={r.n}, runs={r.runs}",
                            axis=1)
        wide = t.pivot_table(index=["family", "setting"], columns=col, values="cell", aggfunc="first").fillna("")
        lines += [f"### {title}", "", wide.reset_index().to_markdown(index=False), ""]
    (OUT / "opening_checks.md").write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
