project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    documentclass: article
    pdf-engine: pdflatex
    papersize: letter
    geometry:
      - margin=1in
    fontsize: 10pt
    number-sections: true
    colorlinks: true
