"""Generate the frozen frontier-rerun config from the September no-defector sets.

Writes config/frontier_rerun_20260918.yaml: the September prompts, personas, topics and
the four no-defector game-parameter blocks, plus 24 experiment sets (6 shapes x 4 arms)
that differ from the September `negative_only_reasoning_rerun_*` sets only in the model
and its pinned request profile. Re-run to regenerate; the launcher audits the result
against the September combinations, so hand edits are pointless.
"""
from __future__ import annotations
import copy
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config/experiments_noisy.yaml"
TARGET = ROOT / "config/frontier_rerun_20260918.yaml"

NEW_MODELS = {
    "claude_opus_5": "anthropic/claude-opus-5",
    "gpt56_sol": "openai/gpt-5.6-sol",
}
PROFILES = {
    "september18_opus5": {
        "provider": "anthropic",
        "reasoning": {"thinking": {"type": "adaptive"}, "output_config": {"effort": "high"}},
        "temperature": "default",
        "max_output_tokens": 64000,
    },
    "september18_gemini31pro": {
        "provider": "google",
        "reasoning": {"thinkingConfig": {"thinkingLevel": "high"}},
        "temperature": 0.8,
        "max_output_tokens": 65536,
    },
    "september18_sol_high": {
        "provider": "openai",
        "reasoning": {"reasoning_effort": "high"},
        "temperature": "default",
        "max_output_tokens": 128000,
    },
    "september18_sol_none": {
        "provider": "openai",
        "reasoning": {"reasoning_effort": "none"},
        "temperature": "default",
        "max_output_tokens": 128000,
    },
}
ARMS = {
    "opus5": ("claude_opus_5", "september18_opus5"),
    "gemini31pro": ("gemini_3_1_pro", "september18_gemini31pro"),
    "sol_high": ("gpt56_sol", "september18_sol_high"),
    "sol_none": ("gpt56_sol", "september18_sol_none"),
}
# shape -> (September set to copy, the single no-defector game-params block to keep)
SHAPES = {
    "dyad_game": ("negative_only_reasoning_rerun_dyad_game_claude_n5", "noisy2_crossmodel_negative_game_r3"),
    "dyad_game_myth": ("negative_only_reasoning_rerun_dyad_game_myth_claude_n5", "noisy2_crossmodel_negative_twotask_r3"),
    "dyad_myth_game": ("negative_only_reasoning_rerun_dyad_myth_game_claude_n5", "noisy2_crossmodel_negative_twotask_r3"),
    "population_game": ("negative_only_reasoning_rerun_population_game_claude_n5", "noisy8_crossmodel_negative_game_r3"),
    "population_game_myth": ("negative_only_reasoning_rerun_population_game_myth_claude_n5", "noisy8_crossmodel_negative_twotask_r3"),
    "population_myth_game": ("negative_only_reasoning_rerun_population_myth_game_claude_n5", "noisy8_crossmodel_negative_twotask_r3"),
}


def build():
    src = yaml.safe_load(SOURCE.read_text())
    cfg = {}
    cfg["base_models"] = {**src["base_models"], **NEW_MODELS}
    cfg["llm_profiles"] = {**src["llm_profiles"], **PROFILES}
    for key in ("prompt_templates", "myth_topics", "personas", "game_prompt_additions"):
        cfg[key] = src[key]
    keep = sorted({gp for _, gp in SHAPES.values()})
    cfg["game_params"] = {name: src["game_params"][name] for name in keep}
    cfg["legacy_environmental_experiment_sets"] = src["legacy_environmental_experiment_sets"]
    sets = {}
    for shape, (sept_set, game_params) in SHAPES.items():
        base = src["experiment_sets"][sept_set]
        assert game_params in base["game_params_list"], (shape, game_params)
        for arm, (model_key, profile) in ARMS.items():
            block = copy.deepcopy(base)
            block["models"] = [model_key]
            block["game_params_list"] = [game_params]
            block["llm_settings"] = copy.deepcopy(PROFILES[profile])
            sets[f"frontier_{shape}_{arm}_n5"] = block
    cfg["experiment_sets"] = sets
    return cfg


def main():
    cfg = build()
    header = "# Frozen frontier rerun (2026-09-18): September no-defector protocol on Claude Opus 5,\n# Gemini 3.1 Pro Preview and GPT-5.6 Sol (effort high and none). Generated by\n# scripts/build_frontier_rerun_config.py; do not edit by hand.\n"
    TARGET.write_text(header + yaml.safe_dump(cfg, sort_keys=False, width=1000, allow_unicode=True))
    print(f"wrote {TARGET.relative_to(ROOT)}: {len(cfg['experiment_sets'])} sets, {len(cfg['game_params'])} game-param blocks")


if __name__ == "__main__":
    main()
