#!/usr/bin/env python3
"""Main-frontier mixed-model runs (2026-09-28); dry-run by default.

The 2026-09-18 main frontier trio (Claude Opus 5, Gemini 3.1 Pro, GPT-5.6 Sol at
effort high), each at its D011 request profile, mixed under the unchanged
September informed-noise protocol (no defectors):

- dyads: Opus 5 / Sol, Opus 5 / Gemini, Gemini / Sol; fixed pair; the first-named
  arm sends first (Agent_1) in replicates 0/2/4, the reversed pair in 1/3/5
  (the September mixed-dyad design of D010); 3 pairings x 3 task orders x 6 = 54 runs.
- populations: 8 agents, balanced rotating pairs; Agent_1-2 Gemini 3.1 Pro,
  Agent_3-5 Opus 5, Agent_6-8 GPT-5.6 Sol; 3 task orders x 5 = 15 runs.

Sets are generated by scripts/build_frontier_rerun_config.py into
config/frontier_rerun_20260918.yaml. The plan step proves, before any paid call,
that every non-model input equals the September control cell of the same size
and task order, and that each agent's request equals its homogeneous frontier
profile. The audit re-checks every final and prices it per model from recorded
token usage at standard rates.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import contextlib
import hashlib
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.run_noisy_missing import load_combinations, expected_output_path, check_existing_final, run_missing_job  # noqa: E402
from scripts.rerun_negative_only_crossmodel import TRUNCATION_REASONS  # noqa: E402
from scripts.build_frontier_rerun_config import ARMS, PROFILES, MAIN_MIXED_POPULATION, MAIN_MIXED_NAME, MAIN_MIXED_DYADS  # noqa: E402
from experiments.run_noisy_batch import build_noisy_protocol  # noqa: E402
from src.llm_settings import is_mixed_plan  # noqa: E402
from src.utils import is_exhausted_quota  # noqa: E402
import yaml  # noqa: E402

CONFIG = ROOT / "config/frontier_rerun_20260918.yaml"
SEPTEMBER = ROOT / "config/experiments_noisy.yaml"
OUTPUT = "frontier_mixed_main_20260928"
SHAPES = ("game", "game_myth", "myth_game")
_BASE_MODELS = yaml.safe_load(CONFIG.read_text())["base_models"]
# USD per MTok by provider model, as priced in the 2026-09-18 frontier receipts (verified then).
RATES = {"claude-opus-5": (5.0, 25.0), "gpt-5.6-sol": (4.0, 20.0), "gemini-3.1-pro-preview": (2.0, 12.0)}
# Mean standard-rate cost per agent in the homogeneous 2026-09-18 frontier runs (run cost / agents).
PER_AGENT_USD = {
    2: {"claude-opus-5": {"game": 0.045, "game_myth": 0.405, "myth_game": 0.445},
        "gpt-5.6-sol": {"game": 0.035, "game_myth": 0.420, "myth_game": 0.405},
        "gemini-3.1-pro-preview": {"game": 0.055, "game_myth": 0.565, "myth_game": 0.560}},
    8: {"claude-opus-5": {"game": 0.081, "game_myth": 0.478, "myth_game": 0.501},
        "gpt-5.6-sol": {"game": 0.061, "game_myth": 0.434, "myth_game": 0.435},
        "gemini-3.1-pro-preview": {"game": 0.056, "game_myth": 0.374, "myth_game": 0.410}},
}
# Inputs that legitimately differ from the homogeneous September control cell.
MODEL_ONLY_KEYS = {"model", "agent_models", "llm_request", "replicate_id"}


def require(condition, *message):
    """Validation that survives ``python -O`` (a bare assert would not)."""
    if not condition:
        raise RuntimeError(" ".join(str(part) for part in message))


def _quiet_combinations(name, config):
    with contextlib.redirect_stdout(io.StringIO()):
        return load_combinations(name, str(config))


def _expected(arms):
    """Agent id -> (model slug, profile) for an ordered list of arms."""
    return {f"Agent_{i + 1}": (_BASE_MODELS[ARMS[arm][0]], PROFILES[ARMS[arm][1]]) for i, arm in enumerate(arms)}


def cells():
    """(set name, size, shape, expected agents, expected replicate ids) for every set."""
    out = []
    for shape in SHAPES:
        for pair, (first, second, replicate_ids) in MAIN_MIXED_DYADS.items():
            out.append((f"frontier_main_mixed_dyad_{shape}_{pair}_n3", 2, shape, _expected([first, second]), replicate_ids))
        arms = [arm for arm, count in MAIN_MIXED_POPULATION for _ in range(count)]
        out.append((f"frontier_main_mixed_population_{shape}_{MAIN_MIXED_NAME}_n5", 8, shape, _expected(arms), [0, 1, 2, 3, 4]))
    return out


def plan():
    jobs = []
    references = {}
    for name, size, shape, expected, replicate_ids in cells():
        kind = "dyad" if size == 2 else "population"
        if (kind, shape) not in references:
            reference = [
                c for c in _quiet_combinations(f"negative_only_reasoning_rerun_{kind}_{shape}_claude_n5", SEPTEMBER)
                if c["game_params_name"].endswith(("negative_game_r3", "negative_twotask_r3")) and c["replicate_id"] == 0
            ]
            require(len(reference) == 1, kind, shape)
            references[(kind, shape)] = {k: v for k, v in reference[0]["comparison_inputs"].items() if k not in MODEL_ONLY_KEYS}
        reference_inputs = references[(kind, shape)]
        combos = _quiet_combinations(name, CONFIG)
        require([c["replicate_id"] for c in combos] == replicate_ids, name, [c["replicate_id"] for c in combos])
        for i, c in enumerate(combos):
            require(c["agent_models"] == {a: m for a, (m, _) in expected.items()}, name, c["agent_models"])
            params = c["game_params"]
            require(params["num_agents"] == size, name, "num_agents")
            require(params["pairing_mode"] == ("fixed" if size == 2 else "balanced"), name, "pairing_mode")
            require(params["noise_config"]["inform_agents"] is True, name, "inform_agents")
            if size == 8:
                require(params["show_agent_names"] is False and params["history_policy"] == "self_and_coplayer"
                        and params["coplayer_history_window"] == 3, name, "population history/identity settings")
            request = c["request_plan"].as_dict()
            require(is_mixed_plan(request) and request["model"] == c["model"], name, "mixed request plan")
            for agent_id, (model, profile) in expected.items():
                agent_request = request["agents"][agent_id]
                require(agent_request["model"] == model, name, agent_id, "model")
                require(agent_request["provider"] == profile["provider"], name, agent_id, "provider")
                require(agent_request["policy"] == profile, name, agent_id, agent_request["policy"])
            actual_inputs = {k: v for k, v in c["comparison_inputs"].items() if k not in MODEL_ONLY_KEYS}
            differing = sorted(k for k in set(actual_inputs) | set(reference_inputs) if actual_inputs.get(k) != reference_inputs.get(k))
            require(not differing, name, "non-model inputs differ from September control", differing)
            require(params.get("defector_ratio", 0) == 0 and params.get("random_defection_probability", 0) == 0, name, "defectors")
            game, _ = build_noisy_protocol(c, i)
            require(len(game.defector_agent_ids) == 0 and game.random_defection_probability == 0, name, "defectors in protocol")
            require(not game.punishment_enabled, name, "punishment")
            jobs.append({"name": name, "index": i, "combo": c, "size": size, "shape": shape,
                         "path": expected_output_path(c, name, i, OUTPUT)})
    require(len(jobs) == 69 and len({str(j["path"]) for j in jobs}) == 69, f"expected 69 unique jobs, found {len(jobs)}")
    # Two-task and eight-agent jobs are the slow path: start them first.
    jobs.sort(key=lambda j: (0 if "myth" in j["shape"] else 1, 0 if j["size"] == 8 else 1, j["combo"]["replicate_id"], j["name"]))
    return jobs


def estimate(jobs):
    total = {m: 0.0 for m in RATES}
    for j in jobs:
        for agent_request in j["combo"]["request_plan"].as_dict()["agents"].values():
            total[agent_request["provider_model"]] += PER_AGENT_USD[j["size"]][agent_request["provider_model"]][j["shape"]]
    return total


def audit(job):
    c, path, name = job["combo"], job["path"], job["name"]
    check_existing_final(path, c)
    d = json.loads(path.read_text())
    m = d["run_metadata"]
    request = c["request_plan"].as_dict()
    require(m["defector_count"] == 0 and m["random_defection_probability"] == 0, path, "defectors")
    require(not m["code_dirty"], path, "produced from a dirty checkout")
    require(m["llm_request"] == request and m["llm_provider"] == "mixed", path, "request plan")
    require(m["agent_models"] == c["agent_models"], path, "agent models")
    require(m["noise_config"] == c["game_params"]["noise_config"], path, "noise config")
    require(set(d["agents"]) == set(request["agents"]), path, "agent ids")
    calls = 0
    cost = {model: 0.0 for model in RATES}
    for agent_id, a in d["agents"].items():
        expected = request["agents"][agent_id]
        require(a["model"] == expected["model"], path, agent_id, a["model"])
        provider_model = expected["provider_model"]
        ir, orr = RATES[provider_model]
        for e in a.get("interaction_history", []):
            r = e.get("response") or {}
            if r.get("response_source", "llm") != "llm":
                continue
            u = r.get("usage") or {}
            require(u.get("request_settings") == expected, path, agent_id, "per-call request settings differ from the plan")
            require(u.get("outcome") == "complete" and u.get("finish_reason") not in TRUNCATION_REASONS, path, agent_id, "truncated or incomplete call", u.get("finish_reason"))
            calls += 1
            output = (u.get("output_tokens") or 0) + ((u.get("reasoning_tokens") or 0) if expected["provider"] == "google" else 0)
            cost[provider_model] += ((u.get("input_tokens") or 0) * ir + output * orr) / 1e6
    require(calls > 0, path, "no LLM calls recorded")
    return {"path": str(path.relative_to(ROOT)), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "set": name,
            "num_agents": job["size"], "agent_models": c["agent_models"], "task_order": job["shape"],
            "replicate_id": c["replicate_id"], "calls": calls, "standard_rate_usd_by_model": cost,
            "standard_rate_usd": sum(cost.values())}


STAGES = {
    "smoke": lambda j: j["shape"] == "game" and j["combo"]["replicate_id"] == 0 and (j["size"] == 8 or j["name"].endswith("_opus5_sol_n3")),
    "dyads": lambda j: j["size"] == 2,
    "populations": lambda j: j["size"] == 8,
    "all": lambda j: True,
}


def main():
    os.chdir(ROOT)  # workers write finals relative to the cwd; the audit reads ROOT-relative paths
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--stage", choices=sorted(STAGES), required=True)
    p.add_argument("--workers", type=int, default=6)
    p.add_argument("--execute", action="store_true")
    p.add_argument("--audit-only", action="store_true")
    args = p.parse_args()
    require(1 <= args.workers <= 20, "--workers must be 1-20")
    selected = [j for j in plan() if STAGES[args.stage](j)]
    pending, receipts = [], []
    for j in selected:
        if j["path"].exists():
            receipts.append(audit(j))
        else:
            pending.append(j)
    est = estimate(pending)
    n_dyad = sum(j["size"] == 2 for j in pending)
    print(f"VALIDATED STAGE={args.stage} N={len(selected)} EXISTING={len(receipts)} PENDING={len(pending)} "
          f"(dyads {n_dyad}, populations {len(pending) - n_dyad}) NO_DEFECTORS=1", flush=True)
    print(f"MODEL=mixed({','.join(RATES)}) N={len(pending)} WORKERS={args.workers} EST_COST=${sum(est.values()):.2f} "
          f"({', '.join(f'{k} ${v:.2f}' for k, v in est.items())}; +20% allowance ${1.2 * sum(est.values()):.2f})", flush=True)
    if args.audit_only:
        require(not pending, f"{len(pending)} runs missing")
    elif not args.execute:
        print("DRY RUN: pass --execute to launch", flush=True)
        return
    if args.execute and pending:
        require(not subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True).strip(), "Clean checkout required")
        os.environ["HF_DATASET_AUTO_UPLOAD"] = "0"
        os.environ["TRUST_BATCH_QUIET"] = "1"
        logdir = str(ROOT / "data/json/noise_experiments" / OUTPUT / "worker_logs")
        workers = min(args.workers, len(pending))
        for attempt in range(1, 11):
            if not pending:
                break
            failed = []
            quota_exhausted = False
            with ProcessPoolExecutor(max_workers=workers) as pool:
                futures = {pool.submit(run_missing_job, j["combo"], j["name"], j["index"], OUTPUT, logdir): j for j in pending}
                for f in as_completed(futures):
                    j = futures[f]
                    if f.cancelled():
                        failed.append(j)
                        continue
                    try:
                        result = f.result()
                        if not result.get("success") and is_exhausted_quota(result.get("error", "")):
                            quota_exhausted = True
                            for queued in futures:
                                queued.cancel()
                            print("BILLING EXHAUSTED: canceling queued jobs; no further retry passes", flush=True)
                        if not result.get("success"):
                            raise RuntimeError(f"Worker failed; inspect {result.get('worker_log')}: {str(result.get('error'))[:300]}")
                        receipt = audit(j)
                        receipts.append(receipt)
                        print(f"COMPLETE {len(receipts)}/{len(selected)} {j['name']} index={j['index']} calls={receipt['calls']} cost=${receipt['standard_rate_usd']:.3f}", flush=True)
                    except Exception as e:
                        print(f"FAILED {j['name']} index={j['index']} {type(e).__name__}: {e}", flush=True)
                        # Never silently resample a final that fails scientific validation.
                        if j["path"].exists():
                            raise
                        failed.append(j)
            if quota_exhausted:
                raise RuntimeError("Provider credits exhausted; top up before resuming. Completed finals preserved.")
            pending = failed
            if pending:
                if attempt == 10:
                    raise RuntimeError(f"{len(pending)} runs failed after ten attempts")
                workers = max(1, min(workers, len(pending)) // 2)
                print(f"CONTINUATION PENDING={len(pending)} WORKERS={workers} ATTEMPT={attempt + 1}", flush=True)
                time.sleep(min(60, 2 ** attempt))
    by_model = {k: sum(r["standard_rate_usd_by_model"][k] for r in receipts) for k in RATES}
    target = ROOT / "data/json/noise_experiments" / OUTPUT / f"{args.stage}_receipt.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps({"stage": args.stage, "runs": len(receipts), "standard_rate_usd": sum(r["standard_rate_usd"] for r in receipts),
                                  "standard_rate_usd_by_model": by_model, "finals": receipts}, indent=2) + "\n")
    print(f"AUDIT PASSED {len(receipts)}/{len(selected)}; cost=${sum(by_model.values()):.2f} {by_model}; receipt={target}", flush=True)


if __name__ == "__main__":
    main()
