#!/usr/bin/env python3
"""Frontier mixed-model eight-agent populations (2026-09-28); dry-run by default.

One composition under the September informed-noise population protocol
(balanced rotating pairing, hidden names, co-player history 3, no defectors):
2 Gemini 3.1 Pro (Agent_1-2), 3 GPT-6 Sol (Agent_3-5) and 3 Claude Opus 5.5
(Agent_6-8); task orders game, game_myth and myth_game; five replicates per
cell (15 runs). Sets are generated by scripts/build_frontier_rerun_config.py
into config/frontier_rerun_20260918.yaml, so each family uses the same pinned
request profile as its homogeneous frontier arm.

The plan step proves, before any paid call, that every non-model input equals
the September ``negative_only_reasoning_rerun_population_*`` control cell and
that each agent's request policy equals its frontier arm's profile. The audit
re-checks every final and prices it per model from recorded token usage at
standard rates.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import contextlib
import hashlib
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.run_noisy_missing import load_combinations, expected_output_path, check_existing_final, run_missing_job  # noqa: E402
from scripts.rerun_negative_only_crossmodel import TRUNCATION_REASONS  # noqa: E402
from scripts.build_frontier_rerun_config import ARMS, PROFILES, MIXED_POPULATION, MIXED_NAME  # noqa: E402
from experiments.run_noisy_batch import build_noisy_protocol  # noqa: E402
from src.llm_settings import is_mixed_plan  # noqa: E402
from src.utils import is_exhausted_quota  # noqa: E402
import yaml  # noqa: E402

CONFIG = ROOT / "config/frontier_rerun_20260918.yaml"
SEPTEMBER = ROOT / "config/experiments_noisy.yaml"
OUTPUT = "frontier_mixed_populations_20260928"
SHAPES = ("game", "game_myth", "myth_game")
_BASE_MODELS = yaml.safe_load(CONFIG.read_text())["base_models"]
# USD per MTok by provider model: Anthropic pricing page (2026-09-23), OpenAI gpt-6-sol model
# page (2026-09-28), Google Gemini 3.1 Pro rate used for the 2026-09-18 frontier receipts.
RATES = {"claude-opus-5-5": (4.0, 20.0), "gpt-6-sol": (2.0, 10.0), "gemini-3.1-pro-preview": (2.0, 12.0)}
# Mean standard-rate cost per agent in the homogeneous frontier populations (8-agent run / 8):
# Opus 5.5 reps3 receipt, Gemini 3.1 Pro main receipt, GPT-5.6 Sol-high main receipt at GPT-6 Sol rates.
PER_AGENT_USD = {
    "claude-opus-5-5": {"game": 0.094, "game_myth": 0.489, "myth_game": 0.480},
    "gpt-6-sol": {"game": 0.031, "game_myth": 0.217, "myth_game": 0.218},
    "gemini-3.1-pro-preview": {"game": 0.056, "game_myth": 0.374, "myth_game": 0.410},
}
# Inputs that legitimately differ from the homogeneous September control cell.
MODEL_ONLY_KEYS = {"model", "agent_models", "llm_request", "replicate_id"}
EXPECTED_MODELS = {}
EXPECTED_POLICIES = {}
_agent = 0
for _arm, _count in MIXED_POPULATION:
    _model_key, _profile = ARMS[_arm]
    for _ in range(_count):
        _agent += 1
        EXPECTED_MODELS[f"Agent_{_agent}"] = _BASE_MODELS[_model_key]
        EXPECTED_POLICIES[f"Agent_{_agent}"] = PROFILES[_profile]
assert _agent == 8


def _quiet_combinations(name, config):
    with contextlib.redirect_stdout(io.StringIO()):
        return load_combinations(name, str(config))


def plan():
    jobs = []
    for shape in SHAPES:
        reference = [
            c for c in _quiet_combinations(f"negative_only_reasoning_rerun_population_{shape}_claude_n5", SEPTEMBER)
            if c["game_params_name"].endswith(("negative_game_r3", "negative_twotask_r3")) and c["replicate_id"] == 0
        ]
        assert len(reference) == 1, shape
        reference_inputs = {k: v for k, v in reference[0]["comparison_inputs"].items() if k not in MODEL_ONLY_KEYS}
        name = f"frontier_mixed_population_{shape}_{MIXED_NAME}_n5"
        combos = _quiet_combinations(name, CONFIG)
        assert [c["replicate_id"] for c in combos] == [0, 1, 2, 3, 4], name
        for i, c in enumerate(combos):
            assert c["agent_models"] == EXPECTED_MODELS, (name, c["agent_models"])
            params = c["game_params"]
            assert params["num_agents"] == 8 and params["pairing_mode"] == "balanced" and params["show_agent_names"] is False
            assert params["history_policy"] == "self_and_coplayer" and params["coplayer_history_window"] == 3
            assert params["noise_config"]["inform_agents"] is True
            request = c["request_plan"].as_dict()
            assert is_mixed_plan(request) and request["model"] == c["model"]
            for agent_id, model in EXPECTED_MODELS.items():
                agent_request = request["agents"][agent_id]
                assert agent_request["model"] == model
                assert agent_request["provider"] == EXPECTED_POLICIES[agent_id]["provider"], (name, agent_id)
                assert agent_request["policy"] == EXPECTED_POLICIES[agent_id], (name, agent_id, agent_request["policy"])
            actual_inputs = {k: v for k, v in c["comparison_inputs"].items() if k not in MODEL_ONLY_KEYS}
            differing = sorted(k for k in set(actual_inputs) | set(reference_inputs) if actual_inputs.get(k) != reference_inputs.get(k))
            assert not differing, (name, "non-model inputs differ from September control", differing)
            assert params.get("defector_ratio", 0) == 0 and params.get("random_defection_probability", 0) == 0
            game, _ = build_noisy_protocol(c, i)
            assert len(game.defector_agent_ids) == 0 and game.random_defection_probability == 0
            assert not game.punishment_enabled
            jobs.append((name, i, c, expected_output_path(c, name, i, OUTPUT)))
    assert len(jobs) == 15 and len({str(j[3]) for j in jobs}) == 15
    # Two-task jobs are the slow, expensive path: start them first.
    jobs.sort(key=lambda j: (0 if "myth" in j[2]["task_order"] else 1, j[1]))
    return jobs


def estimate(jobs):
    total = {m: 0.0 for m in RATES}
    for _, _, c, _ in jobs:
        shape = "_".join(c["task_order"])
        for agent_request in c["request_plan"].as_dict()["agents"].values():
            total[agent_request["provider_model"]] += PER_AGENT_USD[agent_request["provider_model"]][shape]
    return total


def audit(job):
    name, i, c, path = job
    check_existing_final(path, c)
    d = json.loads(path.read_text())
    m = d["run_metadata"]
    request = c["request_plan"].as_dict()
    assert m["defector_count"] == 0 and m["random_defection_probability"] == 0
    assert not m["code_dirty"]
    assert m["llm_request"] == request and m["llm_provider"] == "mixed"
    assert m["agent_models"] == c["agent_models"]
    assert m["noise_config"] == c["game_params"]["noise_config"]
    assert set(d["agents"]) == set(request["agents"])
    calls = 0
    cost = {model: 0.0 for model in RATES}
    for agent_id, a in d["agents"].items():
        expected = request["agents"][agent_id]
        assert a["model"] == expected["model"], (agent_id, a["model"])
        provider_model = expected["provider_model"]
        ir, orr = RATES[provider_model]
        for e in a.get("interaction_history", []):
            r = e.get("response") or {}
            if r.get("response_source", "llm") != "llm":
                continue
            u = r.get("usage") or {}
            assert u.get("request_settings") == expected, (name, agent_id)
            assert u.get("outcome") == "complete" and u.get("finish_reason") not in TRUNCATION_REASONS, (name, agent_id, u.get("finish_reason"))
            calls += 1
            output = (u.get("output_tokens") or 0) + ((u.get("reasoning_tokens") or 0) if expected["provider"] == "google" else 0)
            cost[provider_model] += ((u.get("input_tokens") or 0) * ir + output * orr) / 1e6
    return {
        "path": str(path.relative_to(ROOT)),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "set": name,
        "agent_models": c["agent_models"],
        "task_order": "_".join(c["task_order"]),
        "replicate_id": c["replicate_id"],
        "calls": calls,
        "standard_rate_usd_by_model": cost,
        "standard_rate_usd": sum(cost.values()),
    }


def main():
    os.chdir(ROOT)  # workers write finals relative to the cwd; the audit reads ROOT-relative paths
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--workers", type=int, default=5)
    p.add_argument("--execute", action="store_true")
    p.add_argument("--audit-only", action="store_true")
    p.add_argument("--smoke", action="store_true", help="replicate 0 of the game-only cell (1 run)")
    args = p.parse_args()
    assert 1 <= args.workers <= 20
    jobs = plan()
    if args.smoke:
        jobs = [j for j in jobs if j[2]["task_order"] == ["game"] and j[1] == 0]
        assert len(jobs) == 1
    pending, receipts = [], []
    for j in jobs:
        if j[3].exists():
            receipts.append(audit(j))
        else:
            pending.append(j)
    est = estimate(pending)
    print(f"VALIDATED N={len(jobs)} POPULATIONS_8 COMPOSITION={MIXED_NAME} BALANCED_PAIRING=1 NO_DEFECTORS=1 EXISTING={len(receipts)} PENDING={len(pending)}", flush=True)
    print(
        f"MODEL=mixed({','.join(RATES)}) N={len(pending)} WORKERS={args.workers} "
        f"EST_COST=${sum(est.values()):.2f} ({', '.join(f'{k} ${v:.2f}' for k, v in est.items())}; +20% allowance ${1.2*sum(est.values()):.2f})",
        flush=True,
    )
    if args.audit_only:
        assert not pending
    elif not args.execute:
        print("DRY RUN: pass --execute to launch", flush=True)
        return
    if args.execute and pending:
        assert not subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True).strip(), "Clean checkout required"
        os.environ["HF_DATASET_AUTO_UPLOAD"] = "0"
        os.environ["TRUST_BATCH_QUIET"] = "1"
        logdir = str(ROOT / "data/json/noise_experiments" / OUTPUT / "worker_logs")
        workers = min(args.workers, len(pending))
        for attempt in range(1, 11):
            if not pending:
                break
            failed = []
            quota_exhausted = False
            with ProcessPoolExecutor(max_workers=workers) as pool:
                futures = {pool.submit(run_missing_job, j[2], j[0], j[1], OUTPUT, logdir): j for j in pending}
                for f in as_completed(futures):
                    j = futures[f]
                    if f.cancelled():
                        failed.append(j)
                        continue
                    try:
                        result = f.result()
                        if not result.get("success") and is_exhausted_quota(result.get("error", "")):
                            quota_exhausted = True
                            for queued in futures:
                                queued.cancel()
                            print("BILLING EXHAUSTED: canceling queued jobs; no further retry passes", flush=True)
                        if not result.get("success"):
                            raise RuntimeError(f"Worker failed; inspect {result.get('worker_log')}: {str(result.get('error'))[:300]}")
                        receipt = audit(j)
                        receipts.append(receipt)
                        print(f"COMPLETE {len(receipts)}/{len(jobs)} {j[0]} index={j[1]} calls={receipt['calls']} cost=${receipt['standard_rate_usd']:.3f}", flush=True)
                    except Exception as e:
                        print(f"FAILED {j[0]} index={j[1]} {type(e).__name__}: {e}", flush=True)
                        # Never silently resample a final that fails scientific validation.
                        if j[3].exists():
                            raise
                        failed.append(j)
            if quota_exhausted:
                raise RuntimeError("Provider credits exhausted; top up before resuming. Completed finals preserved.")
            pending = failed
            if pending:
                if attempt == 10:
                    raise RuntimeError(f"{len(pending)} runs failed after ten attempts")
                workers = max(1, min(workers, len(pending)) // 2)
                print(f"CONTINUATION PENDING={len(pending)} WORKERS={workers} ATTEMPT={attempt+1}", flush=True)
                time.sleep(min(60, 2 ** attempt))
    by_model = {k: sum(r["standard_rate_usd_by_model"][k] for r in receipts) for k in RATES}
    target = ROOT / "data/json/noise_experiments" / OUTPUT / ("smoke_receipt.json" if args.smoke else "completion_receipt.json")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps({
        "runs": len(receipts),
        "standard_rate_usd": sum(r["standard_rate_usd"] for r in receipts),
        "standard_rate_usd_by_model": by_model,
        "finals": receipts,
    }, indent=2) + "\n")
    print(f"AUDIT PASSED {len(receipts)}/{len(jobs)}; cost=${sum(by_model.values()):.2f} {by_model}; receipt={target}", flush=True)


if __name__ == "__main__":
    main()
