"""
Filler text pool for the A1 partner-myth control conditions (C2: any-text).

These paragraphs are length-matched to the median GPT-5-Nano baseline myth
(~212 words / ~1226 characters; range ~180-260 words). They are intentionally
non-narrative reference-text prose: no agentive subjects, no plot, no moral,
no first/second person, no cooperative or adversarial signal. The aim is to
supply roughly the same prompt volume and the same wrapper as a real partner
myth, while stripping the genre and content that the A1 hypothesis says is
load-bearing.

The sampler is deterministic given (seed_components) so the same pool entry
is selected for the same agent in the same round across re-runs.
"""

from __future__ import annotations

import hashlib
from typing import Sequence

# Target ~200-220 words each, matching the baseline GPT-5-Nano myth distribution.
FILLER_PARAGRAPHS: Sequence[str] = (
    # 1
    """Basalt is a fine-grained extrusive igneous rock formed from the rapid cooling of low-viscosity lava rich in magnesium and iron. It is the most common volcanic rock on the surface of the Earth and also makes up large portions of the lunar maria, the dark plains visible from terrestrial observation. The mineral composition typically includes plagioclase feldspar, pyroxene, and small amounts of olivine. Columnar jointing, a characteristic pattern of hexagonal fractures, often develops as thick basalt flows contract during cooling. Notable examples of columnar basalt formations include the Giant's Causeway on the coast of Northern Ireland and the Devils Postpile in eastern California. Submarine basalt erupted at mid-ocean ridges constitutes the bulk of oceanic crust, while continental flood basalts such as the Deccan Traps cover regions hundreds of thousands of square kilometres in extent. Weathering of basalt over geological timescales releases calcium, magnesium, and iron into surrounding soils, and the resulting fertility supports productive agriculture in many volcanic regions. Density values typically fall between 2.8 and 3.0 grams per cubic centimetre, somewhat higher than the average for granitic crustal rocks. The temperature of erupting basaltic lava ranges from approximately 1100 to 1250 degrees Celsius, allowing flows to travel many kilometres before solidifying.""",
    # 2
    """The standard musical staff consists of five horizontal lines and four intervening spaces, on which note symbols are placed to indicate pitch and rhythm. A clef positioned at the leftmost edge fixes the pitch range represented by the staff, with the treble clef centring on the G above middle C and the bass clef centring on the F below middle C. Additional ledger lines extend the staff above and below for notes outside its main range. Key signatures, written immediately after the clef, declare which pitches are sharpened or flattened throughout a passage, while time signatures specify the number of beats per measure and the note value that receives one beat. Note shapes encode duration: a hollow note head with no stem represents a whole note lasting four beats in common time, while filled note heads with stems and flags represent successively shorter durations. Rests of equivalent duration occupy the silences between notes. Dynamic markings such as piano, mezzo-forte, and fortissimo indicate relative loudness, and articulation marks such as staccato, legato, and accent describe how individual notes should be sounded. Modern engraving conventions originated in printed editions of European music during the seventeenth century and remain largely unchanged today.""",
    # 3
    """The hydrologic cycle is the continuous circulation of water within the Earth and its atmosphere through evaporation, condensation, precipitation, infiltration, and runoff. Solar radiation drives the evaporation of water from oceans, lakes, rivers, and damp soil, lifting roughly five hundred thousand cubic kilometres of water into the atmosphere each year. Transpiration from vegetation contributes an additional substantial fraction. Once aloft, water vapour cools as it rises and condenses around microscopic aerosol particles, forming the droplets and ice crystals of clouds. Precipitation returns this water to the surface as rain, snow, sleet, or hail, with the form determined by atmospheric temperature profiles. Some precipitation falls directly into oceans, while the rest reaches land, where it may infiltrate into the soil to recharge groundwater aquifers, run off into streams and rivers, or be intercepted by vegetation. Groundwater flows slowly through permeable strata and may emerge at springs or discharge directly into the sea. Rivers transport surface runoff back to the oceans, completing the cycle. The mean residence time of a water molecule varies enormously by reservoir, ranging from about nine days in the atmosphere to thousands of years in deep groundwater and ice sheets.""",
    # 4
    """Container shipping is a mode of intermodal freight transport using standardised steel containers that can be transferred between ships, trains, and trucks without unloading and reloading their contents. The most common container sizes are twenty feet and forty feet in length, both eight feet wide and either eight feet six inches or nine feet six inches tall. The basic accounting unit, the twenty-foot equivalent unit or TEU, allows ports and shipping lines to compare throughput across vessels of different sizes. The largest contemporary container ships exceed twenty-four thousand TEU capacity and require purpose-built terminals with deepwater berths and gantry cranes capable of reaching across the deck. Ports such as Shanghai, Singapore, and Rotterdam handle the highest volumes worldwide. Standardisation, introduced commercially in the late nineteen-fifties and codified by international agreement in the following decade, dramatically reduced cargo handling costs and stevedoring labour while increasing transit speed. Empty container repositioning constitutes a persistent imbalance in global trade, since outbound and inbound flows differ in volume between trading regions. Terminal operating systems track container locations using transponders, optical character recognition, and global positioning data to coordinate stacking and retrieval.""",
    # 5
    """Photosynthesis is the biochemical process by which plants, algae, and certain bacteria convert light energy, principally from sunlight, into chemical energy stored in carbohydrate molecules. The light-dependent reactions take place in the thylakoid membranes of chloroplasts, where chlorophyll pigments absorb photons and drive the splitting of water molecules into oxygen, protons, and electrons. The released electrons travel through a chain of membrane-bound carriers, generating a proton gradient that powers the synthesis of adenosine triphosphate. Reduced nicotinamide adenine dinucleotide phosphate is also produced. The light-independent reactions, often called the Calvin cycle, occur in the surrounding stroma and use these energy carriers to fix atmospheric carbon dioxide into three-carbon sugar phosphates. Six turns of the cycle yield one molecule of glucose. Variations on this scheme have evolved in different lineages: C4 plants spatially separate initial carbon fixation from the Calvin cycle to suppress wasteful photorespiration, and CAM plants temporally separate the same steps to conserve water in arid environments. Net global terrestrial primary production is estimated at roughly one hundred billion tonnes of carbon per year. Marine photosynthesis by phytoplankton contributes a comparable additional total.""",
    # 6
    """Concrete is a composite construction material composed of aggregate, typically gravel and sand, bound together with a fluid cement that hardens over time. The most widely used cement is portland cement, a finely ground mixture of limestone and clay calcined at high temperature. When water is added, hydration reactions form interlocking calcium silicate hydrate crystals that bind the aggregate into a solid mass. Compressive strength develops gradually, reaching most of its design value at twenty-eight days of curing, although development continues at a slower rate for years. Steel reinforcement embedded in concrete compensates for its low tensile strength, producing reinforced concrete suitable for beams, slabs, and frames. Prestressed concrete tensions the reinforcement before or after casting to keep the surrounding concrete in compression under service loads. Admixtures such as plasticisers, retarders, and air-entrainers modify workability, setting time, and durability. Annual global production of cement exceeds four billion tonnes, and associated carbon dioxide emissions account for a substantial fraction of all industrial greenhouse gas output. Research into supplementary cementitious materials, including fly ash and ground granulated blast furnace slag, aims to reduce this footprint while preserving the structural performance that concrete uniquely combines with low cost.""",
    # 7
    """A fountain pen is a writing instrument that delivers liquid ink from an internal reservoir to a metal nib through a feed system that exploits capillary action and gravity. The nib, traditionally formed from steel or gold and tipped with a hard wear-resistant alloy such as iridium, splits at its point to allow ink to flow down a thin slit. Beneath the nib, a feed channel maintains a balance between ink supply and air return, preventing both starvation and flooding. Reservoir designs include simple eyedropper filling, lever-actuated rubber sacs, piston converters with internal threaded plungers, and cartridge systems that accept replaceable plastic ink containers. Modern manufacturers offer a wide range of nib widths, from extra fine to broad, and specialty grinds such as italic, oblique, and stub varieties that produce line variation according to writing angle. Inks are typically water-based and may be dye-based for vibrancy or pigment-based for permanence and water resistance. Famous historical refinements include the development of the lever filler in nineteen-eight and the first commercially successful piston filler in the nineteen-twenties. Maintenance involves periodic flushing with cool water to remove dried residue and prevent clogging.""",
    # 8
    """The Doppler effect describes the change in observed frequency of a wave caused by relative motion between the source of the wave and the observer. When the source approaches the observer, successive wave crests are emitted from progressively nearer positions, compressing the spacing between them and shifting the perceived frequency upward. Recession produces the opposite effect, lengthening the apparent wavelength. The effect was first described mathematically for sound waves in eighteen-forty-two and confirmed experimentally three years later using musicians playing on a moving railway carriage. Analogous shifts occur for electromagnetic radiation, although the formulas must account for the constancy of the speed of light and yield the relativistic Doppler equation. Astronomers exploit the optical Doppler shift to measure radial velocities of stars and galaxies, with the systematic redshift of distant galaxies providing key evidence for the expansion of the universe. Radar systems use the same principle to determine the speed of vehicles and weather targets, and medical ultrasound imaging applies it to visualise blood flow within the body. The magnitude of the shift is small for everyday velocities relative to the wave speed but becomes substantial when source and observer recede at appreciable fractions of the propagation speed.""",
    # 9
    """Sourdough bread is leavened by a stable culture of wild yeasts and lactic acid bacteria maintained in a flour-and-water mixture known as a starter. The yeasts produce carbon dioxide that aerates the dough, while the bacteria contribute lactic and acetic acids that lower the pH, develop the characteristic tangy flavour, and inhibit spoilage organisms. A mature starter typically contains stable populations dominated by Lactobacillus and related genera together with one or several yeast species, often Saccharomyces or Candida. Bakers refresh the starter by feeding it a fixed ratio of fresh flour and water at regular intervals, discarding the excess. The dough is mixed by combining flour, water, salt, and a portion of the active starter, then allowed an extended bulk fermentation lasting several hours. Folding at intervals develops the gluten network without intensive kneading. After shaping, loaves undergo a final proof, often refrigerated overnight to deepen flavour, before being baked at high temperature in a covered vessel that traps steam and produces a crisp crust. The slow fermentation also breaks down some of the gluten and phytic acid in the flour, which some consumers find improves digestibility. Loaf characteristics vary widely according to flour type, hydration level, and ambient temperature.""",
    # 10
    """The transistor is a three-terminal semiconductor device that controls the flow of electric current through one pair of terminals by applying a voltage or current to the third. The bipolar junction transistor, introduced in nineteen-forty-eight, uses a thin doped base region between an emitter and a collector, with carrier injection across the emitter junction modulating collector current. The metal-oxide-semiconductor field-effect transistor, which came to dominate digital electronics, uses an insulated gate electrode to induce a conducting channel in an underlying semiconductor body. Complementary pairs of n-channel and p-channel devices fabricated together form CMOS logic, the basis of nearly all contemporary processors and memory chips. Continued miniaturisation, often summarised as Moore's law, has reduced the linear dimensions of transistor features from several micrometres in the nineteen-seventies to a few nanometres today, with billions of devices now integrated onto a single chip. Power dissipation rises with switching frequency and density, requiring sophisticated cooling and increasingly varied circuit architectures. Beyond digital logic, discrete and integrated transistors serve as amplifiers, voltage regulators, switches in power electronics, and sensors. Manufacturing relies on photolithography, controlled doping, thin-film deposition, and chemical etching performed under cleanroom conditions to maintain extreme purity.""",
)


def get_filler_text(seed_key: str) -> str:
    """Return one filler paragraph deterministically chosen by seed_key.

    seed_key should be a stable string that varies across the contexts where
    you want different fillers to appear (e.g. f"{run_seed}|{agent_id}|{turn}").
    Identical seed_keys always return the same paragraph, which keeps re-runs
    reproducible.
    """
    digest = hashlib.sha256(seed_key.encode("utf-8")).digest()
    idx = int.from_bytes(digest[:8], "big") % len(FILLER_PARAGRAPHS)
    return FILLER_PARAGRAPHS[idx]
